# Generated by Django 5.0.3 on 2024-08-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otpcodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcodemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
